sequenceDiagram

  participant C as Socket.io Client
  participant S as Socket
  participant R as Room
  participant RS as Room systems<br>(many)
  participant Srv as Server Object
  participant L as User left listeners<br>(many)

  C ->> +S: emits 'leave-room' with roomID
  S ->> +Srv: getClient(socket.id)
  Srv -->> -S: returns client object
  S ->> +Srv: getRoom(roomID)

  Srv -->> -S: returns room object

  loop each attached system
    S ->> +R: removeClient(client)
    R ->> +RS: getEvents(room, client)
    RS -->> -R: returns system events
    loop each event
      R -) S: unregister event listener<br>for {roomID}/{event.name}
    end
  end

  R ->> S: leave socket room with roomID

  opt last client in room
    loop each system
      R->>+RS: sleep()
      deactivate RS
    end
  end

  opt last client of user in the room
    loop each listener
      R ->> +L: call listener (client.user)
      deactivate L
    end
  end

  loop each attached system
    R ->> +RS: onClientLeft(room, client)
    RS -->> -R: system state
  end
  

  R -->> -S: returns room systems current state
  S ->> -C: calls callback<br>with system current state


